config/routes.rb
Rajco::Application.routes.draw do
  # mount Monologue::Engine, at: '/blog'
  resources :categories

get 'products/update_image' => 'products#update_image' , :as => :update_image
get 'products/find_update_image/:id' => 'products#find_update_image' , :as => :find_update_image
get 'products/do_update_image/:id' => 'products#do_update_image' , :as => :do_update_image
post 'products/final_update/:id' => 'products#final_update' , :as => :final_update
  #match 'users/sign_up' => redirect('/home')
  resources :products do
    collection do
      
    end
  end

# get 'products/product_search' => 'products#product_search' , :as => :product_search 
  devise_for :users
  resources :admin do
    collection do
      
    end
  end 

get 'home/cataloges' => 'home#cataloges' , :as => :cataloges
#get 'product/update_image' => 'product#update_image' , :as => :update_image
   resources :home do
    collection do
      get 'product_search'
      get 'search'
      get 'aboutus'
      get 'contact'
      get 'store_finder'
      get 'tearms'
      get 'privacy'
      #get 'check_fun'

    end
    member do
      get 'product'
    end
   end
   root :to => 'home#index'
   get 'home/category_view/:id' => 'home#category_view' , :as => :category_view
   get 'home/category/:id' => 'home#category' , :as => :home_cat
   # get 'home/product_view/:id' => 'home#product_view' , :as => :product 
   #get 'home/product_search' => 'home#product_search' , :as => :product_search
 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #caches_page :index , :category_view , :product
  def index
    #@ip = request.remote_ip
    @category = Category.where(category_id: nil)
  end

  def category
    ids = Category.find(params[:id])
    @sub = Category.where(category_id: ids.id)
  end

  def cataloges
    @categories = Category.where(category_id: nil)
    puts "hhhhhhhsssssss#{@categories.inspect}"
    puts "ddddddddddddddd#{@categories[0]['id']}"
    id = @categories[0]['slug']
    #@category = Category.find_by_slug(id)
    @category = Category.where(category_id: nil)
      puts "ffffffffffffffggggg"
      @products=[]
      @category.each do |c|
        @products << c.products
      end
    #@products = @category.products
   
  end

  def category_view
    @categories = Category.where(category_id: nil)
  	@category = Category.find_by_slug(params[:id])
    if @category.category_id.nil? 
      ids= Category.find_by_slug(params[:id])
      @product=[]
      cat = Category.where(category_id: ids.id)
      cat.each do |c|
        prod = c.products
        @product << prod
      end
    else
  	@products = @category.products
  end
  end

  def product
  	@product = Product.find_by_slug(params[:id])
  end

  def product_search
    @product = Product.all
    @product_name = []
    @product.each do |p|
      @product_name << {value: p.name.strip , url: "/home/#{p.slug}/product"}
    end
    respond_to do |format|
       
      format.json { render :json => @product_name }
    end
    end

    def search
      
    end

    def aboutus
      
    end

    def contact
      
    end

    def store_finder
      
    end

    def tearms
      
    end

    def privacy
      
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/aboutus.html.erb
<%=content_for :about do %>
<title>Rajco | About</title>
<%end%>
<section class="light-grey-body content-border">
<div class="push"></div>
<div class="wrapper">
<h2>About Us</h2>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
<div class="push"></div>
</div>
</section>

app/views/home/category.html.erb
<script>
			$(document).ready(function() {
        var slider = $('#slider').leanSlider({
            directionNav: '#slider-direction-nav',
            controlNav: '#slider-control-nav'
        });
    });
		</script>
<section class="wrapper">
	<ul class="submenu-content">
    	<li><label><%=params[:id].titleize%> <i class="spacing-letter"></i> I</label></li>
       	<%@sub.each_with_index do |sc, i|%>
        <%break if i == 4%>
        	<li><%=link_to sc.name , (category_view_path sc)%></li>
        <%end%>
    </ul>
</section>
<div class="clearfix"></div>
<section class="slider-content">

		<div id="slider">
            <div class="slide1">
            	<%=image_tag('1.jpg')%>
                
            </div>
            <div class="slide2">
                <%=image_tag('2.jpg')%>
            </div>
            <div class="slide3">
                <%=image_tag('3.jpg')%>
            </div>
            
        </div>
        
        <div id="slider-control-nav"></div>
	
    <div class="clearfix"></div>
</section>

<section class="bg-light-grey content-border content-01">
<div class="wrapper">
	<div class="push"></div>
    <div class="row product-row">
    	<%@sub.each do |sc|%>
    	<div class="product-content prd-cnt-bottom ">
            <div class="product-inner">
                <div class="product-rollover">
                    <%=link_to 'see now', (category_view_path sc) , :class => "rollover-link"%>
                </div>
                <%=image_tag(sc.photo(:medium), :width => 470 ,:title => "#{sc.photo_file_name}" , :alt => "#{sc.photo_file_name}")%>
                
                </div>
                <div class="product-bottom">
                    <p><%=sc.name%></p>
                    <%=link_to 'see now', (category_view_path sc) , :class => "link-arrow-red"%>
                </div>
        </div>
        <%end%>
    </div>
</div>
</section>

app/views/home/category_view.html.erb
    <%=content_for :category do %>
    <title>Rajco Categories</title>
    <meta property="og:title"                       content="Rajco Categories">  
<meta property="og:description"                 content="Welcome to rajco Shop for rajco track suits, warmup suits, winter jackets and rain jackets view new collections for rajco Originals">
<meta property="og:site_name"                   content="Rajco" />
<meta property="og:url"                         content="http://www.global.adidas.com" />




<meta name="title"                       content="Rajco Categories">  
<meta name="description" content="Welcome to rajco Shop for rajco track suits, warmup suits, winter jackets and rain jackets view new collections for rajco Originals"/>
<meta name="keywords" content="rajco, fitness,  outdoor, polo shirts, rain jackets, soccer set, tshirts, track suit"/>
<%end%>
<section class="light-grey-body content-border">
<div class="push"></div>
<div class="wrapper">
    <div>
        <ul class="page-breadcrumb">

            <li><%=link_to 'Back' , ('/') , :class=> "bck-btn"%> | </li>
            <li><a href="/">Home</a><span class="divider"></span> </li>
            <%abc = params[:id].gsub("-"," ")%>
            <li><a href="/home/category_view/<%=params[:id]%>"><%= abc.titleize%></a></li>
        </ul>
        <div class="clearfix"></div>
        <h3 class="heading-one"><strong>Rajco clothing</strong> <span class="heding-one-text"></span></h3>
    </div>
    <div class="clearfix"></div>
    <div class="row">
    <div class="col-lg-3 left-aside">
        <aside class="left-nav">
            <h4>Product</h4>
            <div id="masterdiv" class="select-catagories-main">
            <div class="select-catagories">  
                <a href="/home/category_view/<%=params[:id]%>" class="catag-active"> <strong><%= abc.titleize%></strong></a>
                
            </div>
           <!--  <a href="#" class="pull-right clear-catagories">Clear all</a> -->
            <div class="clearfix"></div>
        </div>
        
        </aside>
        <aside class="left-nav">
            <h4>Products</h4>
            <%@categories.each do |c|%>
            <div id="masterdiv">
                <div class="leftnav-sep">
                <div class="menutitle"><span onclick="SwitchMenu('<%=c.id%>')" class="masterarrow"><%=image_tag('arrow-down-black.png' ,:width => 12, :height => 12)%></span><%=link_to c.name , (category_view_path c)%></span></div>
                <%cat = Category.where(category_id: c.id)%>
                    <%if cat.present?%>
                        
                            <span class="submenu" id="<%=c.id%>">
                            <% cat.each do |sc| %>
                               <%=link_to sc.name , (category_view_path sc)%><br>
                            <%end%>
                            </span>
                            <div style="height:5px;"></div>
                    <%end%>      
                 </div>

            </div>
            <%end%>

        </aside>
        <div class="clearfix"></div>
        
    </div>
    <div class="col-lg-9 product-container">
        <div class="product-top-banner">
            <div class="pull-right">
                <label>Show:</label>
                <select>
                    <option>24</option>
                    <option>25</option>
                    <option>26</option>
                    <option>27</option>
                </select>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="product-thumb-main">
             <%if @products.present?%>
                 <%@products.each do |p|%>   
                    <div class="porduct-thubnail">
                        <%=link_to image_tag(p.images[0].photo.url(:medium) , :width => 250 , :height => 250, :title => "#{p.images[0].photo_file_name}" , :alt => "#{p.images[0].photo_file_name}"), ("/home/#{p.slug}/product")%>
                        <div class="logo-prd"><%=image_tag('rajco-logo-prd.png', :width => 40)%></div>
                        <p><%= abc.titleize%></p>
                    </div>
                 <%end%>   
            <%elsif @product.present?%>
                <%@product.each do |p|%>
                    <%if p.present?%>
                         <%img = Image.where(product_id: p[0].id)%>
                        <div class="porduct-thubnail">
                            <%=link_to image_tag(img[0].photo.url(:medium) , :width => 250 , :height => 250 ,:title => "#{img[0].photo_file_name}" , :alt => "#{img[0].photo_file_name}"), ("/home/#{p[0].slug}/product")%>

                            <div class="logo-prd"><%=image_tag('rajco-logo-prd.png', :width => 40)%></div>
                            <p><%= abc.titleize%></p>
                        </div>
                    <%end%>
                <%end%>
            <%else%>
                <p style="color:#E83921 !important;">No product for this category</p>
            <%end%>
        </div>    
        <div class="clearfix"></div>
        <div class="product-top-banner">
            <div class="pull-right">
                <label>Show:</label>
                <select>
                    <option>24</option>
                    <option>25</option>
                    <option>26</option>
                    <option>27</option>
                </select>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    </div>
            
        <div class="clearfix"></div>
        <div class="push"></div>
</div>
</section>

app/views/home/contact.html.erb
<%=content_for :contact do %>
<title>Rajco | Contact</title>
<%end%>
<section class="light-grey-body content-border">
<div class="push"></div>
<div class="wrapper">
<h2>Contact</h2>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
<div class="push"></div>
<p>Phone 	: +92321-9876543</p>
<p>Email 	: info@rajco.com</p>
<p>Fax 	 	: +92423-7658902</p>
<p>Address  : Sector A North L.A</p>
<div class="push"></div>
<div class="push"></div>


</div>
</section>

app/views/home/index.html.erb
<script>
			$(document).ready(function() {
        var slider = $('#slider').leanSlider({
            directionNav: '#slider-direction-nav',
            controlNav: '#slider-control-nav'
        });
    });
		</script>
<%=content_for :index do %>
<title>Rajco Official Website | Rajco</title>
<meta property="og:title"                       content="Rajco Official Website | Rajco">  
<meta property="og:description"                 content="Welcome to rajco Shop for rajco track suits, warmup suits, winter jackets and rain jackets view new collections for rajco Originals">
<meta property="og:site_name" 					content="Rajco" />
<meta property="og:url" 						content="http://www.global.adidas.com" />

<meta name="title"                       content="Rajco Official Website | Rajco">  
<meta name="description" content="Welcome to rajco Shop for rajco track suits, warmup suits, winter jackets and rain jackets view new collections for rajco Originals"/>
<meta name="keywords" content="rajco, fitness,  outdoor, polo shirts, rain jackets, soccer set, tshirts, track suit"/>
<%end%>



<section class="slider-content">

		<div id="slider">
            <div class="slide1">
            	<%=image_tag('1.jpg')%>
                
            </div>
            <div class="slide2">
                <%=image_tag('2.jpg')%>
            </div>
            <div class="slide3">
                <%=image_tag('3.jpg')%>
            </div>
            
        </div>
        
        <div id="slider-control-nav"></div>
	
    <div class="clearfix"></div>
</section>
<section class="bg-light-grey content-border content-01">
<div class="wrapper">
	<div class="push"></div>
	<div class="row product-row">
		<%@category.each do |c|%>
	    	<div class="product-content prd-cnt-top">
	            <div class="product-inner">
	                <div class="product-rollover">
	                	<%=link_to 'see now', (home_cat_path c) , :class => "rollover-link"%>
	                </div>
	                <%=image_tag(c.photo.url(:medium), :width => 400, :height => 180,:title => "#{c.photo_file_name}" , :alt => "#{c.photo_file_name}")%>
	                </div>
	                <div class="product-bottom">
	                    <p><%=c.name%></p>
                    <%=link_to 'SEE NOW', (home_cat_path c), :class => "link-arrow-red"%>
	                </div>
	         </div>
	    <%end%>    
    </div>
</div>
</section>

app/views/home/privacy.html.erb
<%=content_for :privacy do %>
<title>Rajco | Privacy Policy</title>
<%end%>
<section class="light-grey-body content-border" style="min-height:700px;">
<div class="push"></div>
<div class="wrapper">
<h2>Privacy Policy</h2>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
<div class="push"></div>
</div>
</section>

app/views/home/product.html.erb
<script type="text/javascript">
function chang_image(obj,tit,des){
		
	$("#changer").attr("src", obj);
    $("#preview").attr("src", obj);
	 $("#changer").attr("data-large", obj);
     $("#changer").attr("alt", tit);
     $("#desp").empty();
     $("#desp").append( "<strong>Code</strong> "+des );

	 
	return false;
}

$(function() {
$( "#tabs" ).tabs();
});
jQuery(function(){

    $('.my-foto').imagezoomsl({ 

        zoomrange: [2, 2]   
    });  
});
</script>
<%=content_for :product do %>
<title>Rajco Products</title>
<meta property="og:title"                       content="Rajco Products">  
<meta property="og:description"                 content="Welcome to rajco Shop for rajco track suits, warmup suits, winter jackets and rain jackets view new collections for rajco Originals">
<meta property="og:site_name" 					content="Rajco" />
<meta property="og:url" 						content="http://www.global.adidas.com" />

<meta name="title"                       content="Rajco Categories">  
<meta name="description" content="Welcome to rajco Shop for rajco track suits, warmup suits, winter jackets and rain jackets view new collections for rajco Originals"/>
<meta name="keywords" content="rajco, fitness,  outdoor, polo shirts, rain jackets, soccer set, tshirts, track suit"/>
<%end%>
<%product = @product.images%>



<section class="content-border">
<div class="push"></div>
<div class="wrapper">
    <div class="list-breadcrub">
    <ul class="page-breadcrumb">
        <li><%=link_to_function 'Back' , 'history.back()' , :class=> "bck-btn"%> | </li>
            <li><a href="/">Home</a><span class="divider"></span> </li>
            <%abc = params[:id].gsub("-"," ")%>
            <li><a href="/home/category_view/<%=params[:id]%>"><%= abc.titleize%></a><span class="divider"></li>
        <li><a href="#">Clouthing</a> </li>
    </ul>
    <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
    <div class="col-lg-6">
    <div class="clearfix my-foto-main" id="content" style="width:442px;" >
    <div class="clearfix">
        <img class="my-foto" id="changer" src="<%=product[0].photo.url%>" width="450" height="450" data-large="<%=product[0].photo.url%>" alt="<%=product[0].photo_file_name%>" style="border:4px solid #666;">
        
    </div>
    <br/>
 <div class="clearfix" >
    <ul id="thumblist" class="clearfix" >
        <%product.each do |p|%>
        
        <li style="float:left; margin-right:10px;"><a href="#" onclick="chang_image('<%=p.photo.url%>' , '<%=p.photo_file_name%>','<%=p.description%>'); return flase;"><%=image_tag(p.photo.url(:thumb), :width => 60 , :height =>60 , :alt => "#{p.photo_file_name}")%></a></li>
        <%end%>
        
    </ul>
    </div>
</div>
    </div>  
    <div class="col-lg-6 product-dsp-container">
        <h3 class="fl no-margin"><%= abc.titleize%></h3>
        <a href="/" class="fr"><%=image_tag('logo.png' , :width=>97)%></a>
        <div class="clearfix"></div>
        <div class="product-box-detail">
            <div class="top">
                <p id="desp"><strong>Color </strong><%= product[0]['description']%></p>
                <a href="#" class="product-icon-detail"><img src="<%=product[0].photo.url%>" width="97" id="preview"></a>
            </div>
            <div class="product-detail-bottom">
                <a href="#" class="btn-blue-one">Store Locator</a>
            </div>
        </div>
        <div class="clearfix"></div>
        
    </div>
    <div class="clearfix"></div>
    <div class="push"></div>
</div>
</div>
</section>

<section class="prd-dtl-btm">
    <div class="wrapper">
    <div id="tabs" class="tab-social">
        <ul>
        <li><a href="#tabs-1">Overview</a></li>
        <li><a href="#tabs-2">Technology</a></li>
        </ul>
        <div id="tabs-1">
            <h1>Predator Instinct FG Boots</h1>
            <p>When the pitch demands the most technical play-making, these men's football boots let you make magic happen. Designed with five lethal zones of predator® technology, they are designed for superior control with every touch of the ball. A HYBRIDTOUCH upper blends supple softness with light weight to deliver unmatched touch. The transparent, firm ground outsole and control frame put specialised speed right under your feet.</p>
            <ul class="disptn-cnt">
                <li>Double-layer air mesh upper for maximum breathability</li>
                <li>Suede overlays for support</li>
                <li>Leather lining for great fit and feel</li>
                <li>Cushioned midsole for a comfortable stride</li>
                <li>Leather contrast 3-Stripes and heel patch</li>
            </ul>
        </div>
        <div id="tabs-2">
             <h1>Predator Instinct </h1>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
            <ul class="disptn-cnt">
                <li>Double-layer air mesh upper for maximum breathability</li>
                <li>Suede overlays for support</li>
                <li>Leather lining for great fit and feel</li>
                <li>Cushioned midsole for a comfortable stride</li>
                <li>Leather contrast 3-Stripes and heel patch</li>
            </ul>
        </div>
        
    </div>
    </div>
</section>

app/views/home/search.html.erb
<%=content_for :search do %>
<title>Rajco | Search</title>
<%end%>
<h2 style="text-align:center; color:red; height:100px;">Product with name "<%=params[:query]%>" is not available</h2>

app/views/home/store_finder.html.erb
    <style>
      #map_canvas {
        width: 500px;
        height: 400px;
      }
    </style>
   
    <script>
      function initialize() {
        var map_canvas = document.getElementById('map_canvas');
        var map_options = {
          center: new google.maps.LatLng(44.5403, -78.5463),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(map_canvas, map_options)
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>

<%=content_for :store do %>
<title>Rajco | Stroe Finder</title>
<%end%>
<section class="light-grey-body content-border">
<div class="push"></div>
<div class="wrapper">
  <h3>Site Map</h3>
    <div id="map_canvas"></div>
</div>
<div class="push"></div>
<div class="push"></div>
</section>

app/views/home/tearms.html.erb
<%=content_for :tearms do %>
<title>Rajco | Terms & Conditions</title>
<%end%>
<section class="light-grey-body trm-cnd-cnt content-border" style="min-height:700px;">
<div class="push"></div>
<div class="wrapper">
<h2>Terms and Conditions</h2>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
<div class="push"></div>
</div>
</section>