config/routes.rb
Rajco::Application.routes.draw do
  # mount Monologue::Engine, at: '/blog'
  resources :categories

get 'products/update_image' => 'products#update_image' , :as => :update_image
get 'products/find_update_image/:id' => 'products#find_update_image' , :as => :find_update_image
get 'products/do_update_image/:id' => 'products#do_update_image' , :as => :do_update_image
post 'products/final_update/:id' => 'products#final_update' , :as => :final_update
  #match 'users/sign_up' => redirect('/home')
  resources :products do
    collection do
      
    end
  end

# get 'products/product_search' => 'products#product_search' , :as => :product_search 
  devise_for :users
  resources :admin do
    collection do
      
    end
  end 

get 'home/cataloges' => 'home#cataloges' , :as => :cataloges
#get 'product/update_image' => 'product#update_image' , :as => :update_image
   resources :home do
    collection do
      get 'product_search'
      get 'search'
      get 'aboutus'
      get 'contact'
      get 'store_finder'
      get 'tearms'
      get 'privacy'
      #get 'check_fun'

    end
    member do
      get 'product'
    end
   end
   root :to => 'home#index'
   get 'home/category_view/:id' => 'home#category_view' , :as => :category_view
   get 'home/category/:id' => 'home#category' , :as => :home_cat
   # get 'home/product_view/:id' => 'home#product_view' , :as => :product 
   #get 'home/product_search' => 'home#product_search' , :as => :product_search
 
end

app/views/layouts/_footer.html.erb
<footer class="footer-content">
    <div class="wrapper">
    <div class="row footer-cnt-top">
        <div class="col-lg-2">
            <h4 class="ft-lst-hd">SPORTS</h4>
            <ul class="footer-list">
                <%@category = Category.where(category_id: nil)%>
                <%@category.each do |c|%>
                <li><%=link_to c.name , (home_cat_path c)%></li>
                <%end%>
            </ul>
        </div>
        
        
        
        
        <div class="col-lg-2">
            <h4 class="ft-lst-hd">SERVICE</h4>
            <ul class="footer-list">
                 <li><%=link_to 'Store Finder' , store_finder_home_index_path%></li>
                  <li><%=link_to 'About Us' , aboutus_home_index_path%></li>
                  <li><%=link_to 'Contact Us' ,  contact_us_path%></li>
                
            </ul>
        </div>
        <div class="col-lg-2">
            <h4 class="ft-lst-hd">COMPANY INFO</h4>
            <ul class="footer-list">
                <li><a href="#">Partners</a></li>
                <li><a href="#">Careers</a></li>
                <li><a href="#">Press</a></li>
                <li><a href="#">Corporate Information</a></li>
            </ul>
        </div>
        <div class="col-lg-6">
            <div class="pull-right footer-rajco-details">
            <%=link_to image_tag('logo.png', :width=>130), root_path%>
            <div class="clearfix"></div>
            <div class="social-footer-main">
            <ul class="footer-social-icons pull-right">
             <li><a href='https://www.facebook.com/RajcoIndustries' class='fb' target="_blank"></a></li>
             <li><a href='https://twitter.com/rajcoindustries' class="tw" target="_blank"></a></li>
            </ul>
            <%= link_to 'About us', aboutus_home_index_path, :class => "red ft-abt"%>
            </div>
            <div class="clearfix"></div>
        </p>
            
            <p class="ft-abt-bt grey">© Rajco Industries, Inc.</p>
            <p class="red ft-abt-bt"><%=link_to 'Privacy Policy' , privacy_home_index_path , :class => "red"%> <%=link_to 'Terms & Conditions' , tearms_home_index_path , :class => "red"%></p>
            
            </div>
        </div>
    </div>
    </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="icon" type="image/x-icon" href="/assets/favicon.ico" />
<%= yield :index%>
<%= yield :product%>
<%= yield :category%>
<%= yield :about%>
<%= yield :search%>
<%= yield :contact%>
<%= yield :tearms%>
<%= yield :privacy%>
<%= yield :store%>
<%= stylesheet_link_tag    "application", :media => "all" %>
  	
    <%= javascript_include_tag "jquery-1.8.2.min" %>
    <%= javascript_include_tag "zoomsl-3.0.min" %>
    
    <%= javascript_include_tag "bootstrap" %>
    <%= javascript_include_tag "main" %>
    <%= javascript_include_tag "raphael-min" %>
    <%= javascript_include_tag "jquery.easing" %>
    <%= javascript_include_tag "lean-slider" %>
    <%#= javascript_include_tag "jquery.mosaicflow" %>
    <%= javascript_include_tag "jquery.textcomplete" %>
    <%= javascript_include_tag "jquery-ui" %>
    <%= javascript_include_tag "googleapi" %>

    
  <%= csrf_meta_tags %>
  <script type="text/javascript">
	var ok;
$(function() {

   $.ajax({
                
            type: 'GET',
                       url: "/home/product_search",
                       'data': {
                       },
                       dataType: "json",
           success: function(response) {
                
                 ok = response;
                 
var availableTags = ok;
$( "#tags" ).autocomplete({
source: availableTags,
select: function (event, ui){
    window.location = ui.item.url;
}
});


           },
           error: function(){
               
           }
        }); 


       });


function search_query(){
  
 var val =$('#tags').val();
  red_url = "http://www.rajcoindustries.com/home/search?query="+val;
  //red_url = "http://localhost:3000/home/search?query="+val;
  window.location=red_url;
  
  
}
       </script>	
</head>
<body>


<header class="header-main">
  <div class="wrapper">
  <div class="row">
      <div class="col-lg-2 logo-content">
         <%=link_to image_tag('rajco-logo.png', :width=>110), root_path%>
        </div>
        
        <div class="col-lg-7 frm-hd-pd">
          <form onsubmit="search_query(); return false;" class="form-header-srch">
              <input type="text" class="field-form fl" id="tags" placeholder="Search"/>
                <input type="submit" class="btn_simplesearch fl" />
            </form>
        </div>
        <div class="col-lg-3 header-middle fr">
          <ul class="header-list">
              <li><%= link_to 'Catalogue', cataloges_path %></li>
                <!-- <li><a href="#">Account</a></li>
                <li><a href="#">Store Locator</a></li> -->
            </ul>
          
          
        </div>
    </div>
    </div>
</header>
<nav class="navbar navbar-default" role="navigation">
<div class="wrapper">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%if params[:id].present?%>
        <%ids = Category.find_by_slug(params[:id])%>
        <%end%>
        <%@category = Category.where(category_id: nil)%>
        <%@category.each do |c|%>
        <%if ids.present?%>
        <li <%if c.id == ids.id || c.id == ids.category_id%>class="active" <%end%>><%=link_to c.name , (home_cat_path c)%></li>
        <%else%>
        <li><%=link_to c.name , (home_cat_path c)%></li>
        <%end%>
        
        <%end%>
           <ul class="nav navbar-nav fr right-menu">
       <!-- 
        <li class="dropdown">
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">catalogue <i class="caret"></i></a>
          <ul class="dropdown-menu">
            <li><a href="#">Men</a></li>
            <li><a href="#">Women</a></li>
            
          </ul>
        </li> -->
      </ul>
      </ul>
      
      
    </div>
  
</div>
</nav>
<div class="clearfix"></div>
<%= yield %>


<%= render 'layouts/footer'%>		
</body>
</html>